### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by perin160403** [Sangwan5688/BlackHole#362]
Unable to download after the recent update.

**Comment by flleeppyy** [comment]
Relevant
```
10-24 13:22:35.595 24060 24174 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/492A-1518/Blackhole Music/YouTube' (OS Error: Permission denied, errno = 13)
10-24 13:22:35.595 24060 24174 E flutter : #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117)
10-24 13:22:35.595 24060 24174 E flutter : <asynchronous suspension>
10-24 13:22:35.595 24060 24174 E flutter : #1      Download.prepareDownload (package:blackhole/Services/download.dart:109)
10-24 13:22:35.595 24060 24174 E flutter : <asynchronous suspension>
10-24 13:22:35.595 24060 24174 E flutter : 
```

**Comment by BrightDV** [comment]
@flleeppyy did you grant the permissions needed to the app? (For the files)

**Comment by flleeppyy** [comment]
Yes I have

**Comment by BrightDV** [comment]
Did you try to update the path of your download location?
