### ISSUE TITLE
Plugin Exception on linux

### ISSUE THREAD

**Issue by AnAverageBeing** [Sangwan5688/BlackHole#469]
**Description**
I built it for linux it runs fine but when i try to make backup or restore backup it show PluginException
```
when i create backup it shows this error in console 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:16)
<asynchronous suspension>
#2      createBackup (package:blackhole/Helpers/backup_restore.dart:41)
<asynchronous suspension>
```

and when i try to restore backup it shows this in ui

![image](https://user-images.githubusercontent.com/84959276/209475626-c03380d2-bbb7-469a-b526-8b25f08eeb05.png)

**To Reproduce**
1. flutter build linux --release
2. cd into bundle/ dir
3. ./blackhole
4. run the app and try to restore backup or make new one
**Expected behavior**
ERRORS as decribed above

**Screenshots**
![image](https://user-images.githubusercontent.com/84959276/209475710-29cb161c-e6b7-40cc-affc-f44e46ecc3a9.png)

**Device Details (please complete the following information):**
 - OS: Linux x64
 - Version: pop os latest
 - Device: laptop
 - App Version: latest

**App Logs**
```
/usr/share/blackhole$ ./BlackHole 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      _GrowableList.first (dart:core-patch/growable_array.dart:343)
#1      AudioPlayerHandlerImpl._init (package:blackhole/Services/audio_service.dart:251)
<asynchronous suspension>

flutter: MissingPluginException(No implementation found for method listen on channel receive_sharing_intent/events-text)
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637)
flutter: <asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getInitialText on channel receive_sharing_intent/messages)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      ReceiveSharingIntent.getInitialText (package:receive_sharing_intent/receive_sharing_intent.dart:38)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:16)
<asynchronous suspension>
#2      createBackup (package:blackhole/Helpers/backup_restore.dart:41)
<asynchronous suspension>
```

**Comment by AnAverageBeing** [comment]
@Sangwan5688 can u help me with this??

**Comment by AnAverageBeing** [comment]
Also Song not playing 

LOGS:

```

^C
yatharth@yatharths-laptop:/usr/share/blackhole$ ./BlackHole 
flutter: MissingPluginException(No implementation found for method listen on channel receive_sharing_intent/events-text)
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637)
flutter: <asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getInitialText on channel receive_sharing_intent/messages)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      ReceiveSharingIntent.getInitialText (package:receive_sharing_intent/receive_sharing_intent.dart:38)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method disposeAllPlayers on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      MethodChannelJustAudio.disposeAllPlayers (package:just_audio_platform_interface/method_channel_just_audio.dart:29)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1329)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1329)
<asynchronous suspension>

```

UI NOT RESPONSIVE
