### ISSUE TITLE
When I build the android app on mac os  get the error

### ISSUE THREAD

**Issue by gavinlau** [Sangwan5688/BlackHole#689]
Step1 :When I clone the code and build the android app on mac os  get the error:
../../../../../.pub-cache/hosted/pub.flutter-io.cn/metadata_god-0.5.0/lib/src/bridge_generated.dart:86:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.flutter-io.cn/metadata_god-0.5.0/lib/src/bridge_generated.dart:105:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/gavin/Downloads/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/gavin/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by gavinlau** [comment]
The version 1.15.9 and after, It may be something wrong with   metadata_god: ^0.5.0.

**Comment by gavinlau** [comment]
Then I override the lib: ! flutter_rust_bridge 1.79.0 (overridden) (1.82.1 available)，the apk will install to the android phone,but get error bellow:
```
E/flutter (29083): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libmetadata_god.so': dlopen failed: library "libmetadata_god.so" not found
E/flutter (29083): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (29083): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (29083): #2      createLibraryImpl (package:metadata_god/src/ffi/io.dart:18:27)
E/flutter (29083): #3      initializeDynamicLibrary (package:metadata_god/src/ffi.dart:9:34)
E/flutter (29083): #4      MetadataGod.initialize (package:metadata_god/src/metadata_god_base.dart:31:14)
E/flutter (29083): #5      startService (package:blackhole/main.dart:92:15)
E/flutter (29083): <asynchronous suspension>
E/flutter (29083): #6      main (package:blackhole/main.dart:66:3)
E/flutter (29083): <asynchronous suspension>
E/flutter (29083): 
Syncing files to device CLT AL00...                                867ms
```
the android phone,stucked on the splash screen.

**Comment by gavinlau** [comment]
Because I have changed the hosted url:
#export PUB_HOSTED_URL=https://pub.flutter-io.cn
#export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

**Comment by gavinlau** [comment]
Close it

**Comment by gavinlau** [comment]
It occors again
