### ISSUE TITLE
Arch Linux exception when listening to songs

### ISSUE THREAD

**Issue by 6801318d8d** [Sangwan5688/BlackHole#716]
I'm trying to run it in Arch Linux using AUR's flutter package.

I followed the README instructions to compile from source.

After running the application with `flutter run`, when I try to listen to a song I get the following exception:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: -1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _IdleAudioPlayer._getDurationAtIndex (package:just_audio/just_audio.dart:3407:23)
#2      _IdleAudioPlayer._broadcastPlaybackEvent (package:just_audio/just_audio.dart:3399:17)
#3      _IdleAudioPlayer.seek (package:just_audio/just_audio.dart:3495:5)
#4      AudioPlayer.seek (package:just_audio/just_audio.dart:1129:16)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method disposeAllPlayers on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.disposeAllPlayers (package:just_audio_platform_interface/method_channel_just_audio.dart:29:10)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1341:13)
<asynchronous suspension>
```

**Comment by Sangwan5688** [comment]
Linux isn't supported by just_audio as of now, which is being used by Blackhole to play audio. In future if the support gets added, you can compile it. Or if you want you can use any other audio player like https://pub.dev/packages/audioplayers which support multiple platforms
