### ISSUE TITLE
Connectivity Blind Spot: Persistent Loading in Search Amid Connection Issues

### ISSUE THREAD

**Issue by t-montes** [Sangwan5688/BlackHole#742]
**Describe the bug**
The search bar gives the user no clue about the no-connection, just keeps loading. Also, when there's connection back, keeps loading.

**Steps To Reproduce**
1. Turn off WiFi and Mobile Data on your device
2. Click on the Search Bar
3. Type anything and search for it, keeping your connection off

**Expected behavior**
The screen should show the user a message advertising that there is no internet connection. Also, when the connection is back, the screen should retry the search again.

**Screenshots**
<p align="center">
  <img width="43%" src="https://github.com/Sangwan5688/BlackHole/assets/69558777/54d68134-4301-4767-9d3b-f9329a372452">
</p>

## Device Details
 - OS: Android
 - Version: Android 13
 - Device: Realme
 - App Version: 1.15.9

## App Logs

E/flutter (11763): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: Failed host lookup: 'www.youtube.com' (OS Error: No address associated with hostname, errno = 7), uri=https://www.youtube.com/results?search_query=fearless+pt+ii&sp=EgIQAQ%253D%253D
E/flutter (11763): #0      IOClient.send (package:http/src/io_client.dart:119:7)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #2      YoutubeHttpClient.get (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:86:22)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #3      YoutubeHttpClient.getString (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:70:9)      
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #4      SearchPage.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart:45:19)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #5      retry (package:youtube_explode_dart/src/retry.dart:16:14)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #6      SearchClient.search (package:youtube_explode_dart/src/search/search_client.dart:22:18)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #7      YouTubeServices.fetchSearchResults (package:blackhole/Services/youtube_services.dart:473:39)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763):

**Comment by Sangwan5688** [comment]
I think this got missed somewhere for youtube. I do assume it works fine for saavn. Anyways, it's a good beginner issue if anyone wants to work, feel free to pick it up

**Comment by Smit56R** [comment]
Hey! I am a beginner at contributing to other projects. Should I work on this issue?

**Comment by JitenderBhati** [comment]
I am starting to look into this issue. Anyone else already working on it? If not, I'll take ownership.

**Comment by JitenderBhati** [comment]
Proposing below two solution:

1. Handle network errors gracefully: Wrap YouTube service calls in try-catch blocks. If a SocketException occurs, return an empty list to render the "nothing found" widget. (same behaviour as for saavn service)

2. Monitor connectivity changes: Leverage the existing connectivity_plus plugin to actively monitor network status. If connection drops, display a snackbar indicating "No internet." (already implemented for audio service for setting preferred audio quality)

Need suggestion
