### ISSUE TITLE
MissingPluginException on Windows Build

### ISSUE THREAD

**Issue by r0ld3x** [Sangwan5688/BlackHole#767]
I am on windows 11

i did ```flutter pub get``` which opened a blackhole window on my dekstop 
but when i am clicking any music then i am getting this error 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1369:13)
<asynchronous suspension>
```

**Comment by r0ld3x** [comment]
I tried ```flutter pub add just_audio_windows``` and it worked nvm. :)
