### ISSUE TITLE
Get stuck after I build the Android app

### ISSUE THREAD

**Issue by CarelTian** [Sangwan5688/BlackHole#795]
**bug**
The app has been built and installed in device but it can't continue to run and show interface. There is no error occur in the console.  I am a beginner to Flutter, I don't know how to fix it.

**Here is the console output**
```

This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib\main.dart on sdk gphone x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
D/FlutterArchivePlugin( 4711): onAttachedToEngine - IN
D/FlutterArchivePlugin( 4711): doOnAttachedToEngine - IN
D/FlutterArchivePlugin( 4711): doOnAttachedToEngine - OUT
D/FlutterArchivePlugin( 4711): onAttachedToEngine - OUT
Debug service listening on ws://127.0.0.1:64737/NSxrGq5yml8=/ws
Syncing files to device sdk gphone x86 64...
E/flutter ( 4711): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libmetadata_god.so': dlopen failed: library "libmetadata_god.so" not found
E/flutter ( 4711): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 4711): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 4711): #2      createLibraryImpl (package:metadata_god/src/ffi/io.dart:18:27)
E/flutter ( 4711): #3      initializeDynamicLibrary (package:metadata_god/src/ffi.dart:9:34)
E/flutter ( 4711): #4      MetadataGod.initialize (package:metadata_god/src/metadata_god_base.dart:31:14)
E/flutter ( 4711): #5      startService (package:blackhole/main.dart:94:15)
E/flutter ( 4711): <asynchronous suspension>
E/flutter ( 4711): #6      main (package:blackhole/main.dart:68:3)
E/flutter ( 4711): <asynchronous suspension>
E/flutter ( 4711): 
I/hadow.blackhole( 4711): Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()

```
**Device detail**
```
Windows 11
Android Studio 2023.1
Pixel 6 pro API 33  
```
** android/app/build.gradle**
```

    // remove signingConfigs when running debug version
    /*
    signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

     */

    buildTypes {
        // replace release with "debug" when running on debug version
        debug {
            // TODO: Add your own signing config for the release build.
            // replace with "debug" when running on debug version
            //signingConfig signingConfigs.release
            shrinkResources false
        }
    }

```

**Comment by CarelTian** [comment]
E/EGL_adreno( 2722): tid 2755: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer( 2722): Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff6bfff000, error=EGL_BAD_MATCH
D/EGL_adreno( 2722): eglMakeCurrent: 0x7fff6a44f380: ver 3 1 (tinfo 0x7fff5aad0940)
